//! Synthetic media for `sim/media/` (T-007), generated with ffmpeg; no Twitch media. Live and ad renditions differ
//! in picture and tone (live: `testsrc2` and 440 Hz; ad: SMPTE HD bars and 880 Hz), so a frame can be told apart.
//! Segments are 2 s, one keyframe each (`-g 60` at 30 fps), named `seg-000.ts` (H.264/AAC in MPEG-TS) or `init.mp4`
//! and `seg-000.m4s` (HEVC/AAC in fMP4). The sim writes its own playlists, so ffmpeg's are removed.

use serde_json::Value;
use std::path::Path;
use std::process::Command;

#[derive(Clone, Copy, Debug)]
pub struct Rendition {
    pub folder: &'static str,
    pub size: &'static str,
    /// lavfi video source
    pub picture: &'static str,
    pub tone: u32,
    pub hevc: bool,
    /// H.264 level (`3.1` for `avc1.4D401F`, `3.0` for `avc1.4D401E`), unused for HEVC
    pub level: &'static str,
    /// seconds generated by `cargo run --bin media`
    pub seconds: u32,
}

pub const RENDITIONS: [Rendition; 6] = [
    Rendition { folder: "live-720p", size: "1280x720", picture: "testsrc2", tone: 440, hevc: false, level: "3.1", seconds: 60 },
    Rendition { folder: "ad-720p", size: "1280x720", picture: "smptehdbars", tone: 880, hevc: false, level: "3.1", seconds: 16 },
    Rendition { folder: "live-360p", size: "640x360", picture: "testsrc2", tone: 440, hevc: false, level: "3.0", seconds: 60 },
    Rendition { folder: "ad-360p", size: "640x360", picture: "smptehdbars", tone: 880, hevc: false, level: "3.0", seconds: 16 },
    Rendition { folder: "live-720p-hevc", size: "1280x720", picture: "testsrc2", tone: 440, hevc: true, level: "", seconds: 60 },
    Rendition { folder: "ad-720p-hevc", size: "1280x720", picture: "smptehdbars", tone: 880, hevc: true, level: "", seconds: 16 },
];

/// Encodes `seconds` of a rendition into `dir/<folder>/`.
pub fn generate(dir: &Path, r: &Rendition, seconds: u32) -> Result<(), String> {
    let out = dir.join(r.folder);
    std::fs::create_dir_all(&out).map_err(|e| e.to_string())?;
    let picture = format!("{}=size={}:rate=30", r.picture, r.size);
    let tone = format!("sine=frequency={}:sample_rate=48000", r.tone);
    let mut args: Vec<String> = ["-hide_banner", "-loglevel", "error", "-y", "-f", "lavfi", "-i", &picture, "-f", "lavfi", "-i", &tone]
        .iter()
        .map(|s| s.to_string())
        .collect();
    args.extend(["-t".into(), seconds.to_string(), "-pix_fmt".into(), "yuv420p".into()]);
    if r.hevc {
        args.extend(
            ["-c:v", "libx265", "-preset", "fast", "-tag:v", "hvc1", "-x265-params", "keyint=60:min-keyint=60:scenecut=0:log-level=error", "-b:v", "2000k"]
                .iter()
                .map(|s| s.to_string()),
        );
    } else {
        args.extend(
            ["-c:v", "libx264", "-preset", "veryfast", "-profile:v", "main", "-level", r.level, "-g", "60", "-keyint_min", "60", "-sc_threshold", "0", "-b:v", "2500k"]
                .iter()
                .map(|s| s.to_string()),
        );
    }
    args.extend(["-c:a", "aac", "-b:a", "96k", "-ac", "2", "-f", "hls", "-hls_time", "2", "-hls_list_size", "0"].iter().map(|s| s.to_string()));
    // ffmpeg runs in the rendition folder with relative names: given a Windows path, it wrote init.mp4 to its own
    // working directory instead of the playlist's folder
    if r.hevc {
        args.extend(["-hls_segment_type", "fmp4", "-hls_fmp4_init_filename", "init.mp4", "-hls_segment_filename", "seg-%03d.m4s"].iter().map(|s| s.to_string()));
    } else {
        args.extend(["-hls_segment_filename".to_string(), "seg-%03d.ts".to_string()]);
    }
    args.push("index.m3u8".into());
    let playlist = out.join("index.m3u8");
    let status = Command::new("ffmpeg").args(&args).current_dir(&out).status().map_err(|e| format!("ffmpeg: {e} (is it installed?)"))?;
    if !status.success() {
        return Err(format!("ffmpeg failed for {}: {status}", r.folder));
    }
    let _ = std::fs::remove_file(playlist);
    Ok(())
}

/// Container (ffprobe `format_name`) and codecs of a media file.
pub fn probe(file: &Path) -> Result<(String, Vec<String>), String> {
    let output = Command::new("ffprobe")
        .args(["-v", "error", "-show_entries", "format=format_name:stream=codec_name", "-of", "json"])
        .arg(file)
        .output()
        .map_err(|e| format!("ffprobe: {e} (is it installed?)"))?;
    let json: Value = serde_json::from_slice(&output.stdout).map_err(|e| e.to_string())?;
    let format = json.pointer("/format/format_name").and_then(Value::as_str).unwrap_or("").to_string();
    let codecs = json
        .get("streams")
        .and_then(Value::as_array)
        .map(|s| s.iter().filter_map(|x| x.get("codec_name").and_then(Value::as_str).map(String::from)).collect())
        .unwrap_or_default();
    Ok((format, codecs))
}
